config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "chatroom#index"
  get "login" ,to:"sessions#new"
  post "login" ,to:"sessions#create"
  delete "logout",to: 'sessions#destroy'
  post "message" ,to:"messages#create"
  mount ActionCable.server,at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    validates :body, presence: true
    belongs_to :user 
    scope :custom_display, -> { order(created_at: :desc).last(5)}
    # Ex:- scope :active, -> {where(:active => true)} 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3,maximum: 50}
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||=User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:error]="must be logged in user"
            redirect_to login_path
        end
    end
    
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user 
  def index
    @message=Message.new
    @messages=Message.custom_display
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  
   def create
      
      message=Message.new(message_params)
      message.user=current_user
       if message.save
        ActionCable.server.broadcast "chatroom_channel",{message_mod: message_render(message) }
        
        end
       
     end
     
  private
  def message_params
    params.require(:message).permit(:body)
  end
  def message_render(message)
    render_to_string(partial: 'message', locals: {message: message}) 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect,only: [:new,:create]
  def new
   
  end
  def  create
     user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      flash[:success] = "Welcome to the chatroom"
      redirect_to root_path
    else
      flash.now[:error] = "Something went wrong"
      render 'new'
    end
  end
  def destroy
    session[:user_id]=nil
    flash[:success]="You have successfuly logged out"
      redirect_to login_path
   
  end
  
  private
  def user_params
    params.require(:session).permit(:username,:password)
  end
  def logged_in_redirect
    if logged_in?
      flash[:success]="You already logged in"
      redirect_to root_path
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<div class="p-5 text-center bg-light">
  <i class="fa-solid fa-mug-hot " style="font-size: 30px; color:brown;"></i>
  <h4 class="mb-3">Say Something</h4>
</div>
<div class="container-fluid ">
  <div class="row ">
    <div class="col-8 " >
      <div class="card">
        <div class="card-header bg-black text-white">
          Chat
        </div>
        <div class="card-body " id="messages">
          <div class="h-100 d-flex flex-column">
            <div class="border-bottom p-3">
              <h5>Messages</h5>
            </div>
            <div class="flex-grow-1 overflow-auto p-3" id="message-container">
              <%= render @messages%>
            </div>
          </div>
        </div>
        <div class="card-footer position-relative">
          <%=form_for(@message,url: message_path,remote: false, data: { turbo: "false" }) do |f|%>
            <div class="input-group mb-3 ">
              <%= f.text_field :body, class: 'form-control reset' %>
              <div class="input-group-append ">
                <button class="btn btn-outline-info" style="color: black;">
                  <%= f.submit 'Text ' ,class:"btn border-0" ,style:"color: black;" %>
                  <i class="fas fa-envelope"></i>
                </button>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="col-4 ">
      <div class="card">
        <div class="card-header bg-black text-white" style="color: brown;">
          Online Users
        </div>
        <div class="card-body">
          <div class="nav flex-column nav-pills bg-black  p-2 rounded-3 m-1">
            <a class="nav-link " href="#home"> <i class="fas fa-home"></i> Home</a>
            <a class="nav-link " href="#messages"> <i class="fas fa-envelope"></i> Messages</a>
            <a class="nav-link" href="#friends"><i class="fas fa-user"></i> Profile</a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/chatroom/new.html.erb
<h1>Chatroom#new</h1>
<p>Find me in app/views/chatroom/new.html.erb</p>
<div class="d-flex flex-row mb-3">
    <div class="bg-primary text-white rounded py-2 px-3 mr-2">
        Hello! How are you?
    </div>
    <div class="text-muted small">12:30 PM</div>
</div>
<%= render "shared/errors" , @user%>

app/views/layouts/_messages.html.erb
<% flash.each do |key,msg|%>
    <div class=" alert alert-<%= key == " notice" ? "success" : "danger" %> text-center" role="alert">
        <%= msg %>
    </div>



    <%end%>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-black">
  <div class="container-fluid">
    <%= link_to "ChatRoom" , root_path ,class:"navbar-brand fw-bold text-uppercase "%>
    <button class=" navbar-toggler bg-light" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse fw-semibold" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Imessage</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Messages</a>
        </li>
      </ul>
      <div class=" d-flex nav-sign me-4 ">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 mb-2">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu bg-light   ">
              <%if logged_in? %>
                <li>
                  <%= button_to "Logout" , logout_path , method: :delete,class:"btn border-0"%>
                </li>
              <%else%>
                <li>
                  <%= link_to "Login" , login_path ,class:"dropdown-item "%>
                </li>
              <%end%>
            </ul>
          </li>
        </ul>
        <%if !logged_in?%>
          <%= link_to "Login" , login_path ,class:"btn btn-outline-info  "%>
        <%end%>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatroom</title>
    <%= favicon_link_tag%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" , "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" , "data-turbo-track": "reload" , defer: true %>
  </head>
  <body>
    <%= render "layouts/nav" %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="media mb-3">

    <div class="media-body">
        <h5 class="mt-0">Friend <%=message.user.username%>
        </h5>
        <p class="lfw-bold fst-italic">
            <%= message.body%>
        </p>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%obj.errors.full_messages.each do |msg| %>
            <strong>
                <li>Holy guacamole! <%=msg%>
                </li>
            </strong>
            <%end%>
                <button type="button" class="btn-close btn btn-outline-danger" data-bs-dismiss="alert"
                    aria-label="Close"></button>
    </div>
    <%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>